CREATE TABLE "PUBLIC"."WORKFLOW"(
    "ID_WORKFLOW" INTEGER NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "STATUS" INTEGER NOT NULL
);
ALTER TABLE "PUBLIC"."WORKFLOW" ADD CONSTRAINT "PUBLIC"."WORKFLOW_PK" PRIMARY KEY("ID_WORKFLOW");

CREATE TABLE "PUBLIC"."WORKFLOW_CATEGORY"(
    "ID_CATEGORY" INTEGER NOT NULL,
    "CREATE_AT" TIMESTAMP,
    "DESCRIPTION" VARCHAR(255),
    "LOGO" VARCHAR(255),
    "NAME" VARCHAR(255),
    "STATUS" INTEGER NOT NULL,
    "UPDATE_AT" TIMESTAMP,
    "PARENT_ID_CATEGORY" INTEGER
);
ALTER TABLE "PUBLIC"."WORKFLOW_CATEGORY" ADD CONSTRAINT "PUBLIC"."WORKFLOW_CATEGORY_PK" PRIMARY KEY("ID_CATEGORY");

CREATE TABLE "PUBLIC"."WORKFLOWS_CATEGORIES"(
    "WORKFLOW_ID" INTEGER NOT NULL,
    "CATEGORY_ID" INTEGER NOT NULL
);

ALTER TABLE "PUBLIC"."WORKFLOWS_CATEGORIES" ADD CONSTRAINT "PUBLIC"."FK_CATEGORY_ID_WORKFLOW_ID" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."WORKFLOW"("ID_WORKFLOW");
ALTER TABLE "PUBLIC"."WORKFLOW_CATEGORY" ADD CONSTRAINT "PUBLIC"."FK_PARENT_CATEGORY_ID_CATEGORY_ID" FOREIGN KEY("PARENT_ID_CATEGORY") REFERENCES "PUBLIC"."WORKFLOW_CATEGORY"("ID_CATEGORY");
ALTER TABLE "PUBLIC"."WORKFLOWS_CATEGORIES" ADD CONSTRAINT "PUBLIC"."FK_WORKFLOW_ID_CATEGORY_ID" FOREIGN KEY("WORKFLOW_ID") REFERENCES "PUBLIC"."WORKFLOW_CATEGORY"("ID_CATEGORY");